In [2]:
import numpy as np

In [4]:
p = np.arange(90)+5

In [5]:
print(p)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [8]:
p = np.arange(45)+5 # problem starts here for one dimension   ----question in word document  

In [9]:
print(p)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
pr = p.reshape((3,3,5))

In [13]:
pr.shape

(3, 3, 5)

In [14]:
pr 

array([[[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [17]:
pr =  np.arange(90).reshape((3,2,3,5)) #3 - product , 2 - shift , 3 -   , 5 - product  

In [18]:
pr

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]],


       [[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44]],

        [[45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]],


       [[[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89]]]])

In [20]:
pr = np.random.random((3,5))+100

In [22]:
print(pr)

[[100.3512125  100.05555886 100.19674637 100.7910491  100.85969301]
 [100.7664071  100.32752143 100.69487801 100.87069068 100.77184051]
 [100.28514993 100.83482942 100.48342536 100.78954302 100.30018286]]


In [23]:
pr[1,2]  #row and column index start from 0.

100.69487801202591

In [24]:
pr[2]

array([100.28514993, 100.83482942, 100.48342536, 100.78954302,
       100.30018286])

In [25]:
pr

array([[100.3512125 , 100.05555886, 100.19674637, 100.7910491 ,
        100.85969301],
       [100.7664071 , 100.32752143, 100.69487801, 100.87069068,
        100.77184051],
       [100.28514993, 100.83482942, 100.48342536, 100.78954302,
        100.30018286]])

In [26]:
pr[:,2]

array([100.19674637, 100.69487801, 100.48342536])

In [27]:
x=np.arange(35).reshape(7,5)+100

In [28]:
print(x)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]]


In [29]:
x[1:4]

array([[105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [30]:
x[:,1:4]  #Row and columns when seperated by comma. 

array([[101, 102, 103],
       [106, 107, 108],
       [111, 112, 113],
       [116, 117, 118],
       [121, 122, 123],
       [126, 127, 128],
       [131, 132, 133]])

In [31]:
x[2:4,1:4]

array([[111, 112, 113],
       [116, 117, 118]])

In [34]:
x=np.arange(45).reshape(3,3,5)+10

In [35]:
print(x)

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]]]


In [37]:
x[0]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
x[-1]

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [39]:
x[:,-1]  # 2 dimension reprsentation

array([[20, 21, 22, 23, 24],
       [35, 36, 37, 38, 39],
       [50, 51, 52, 53, 54]])

In [40]:
x[1,0,1] #3 dimension representation for single element

26

In [41]:
x[:,:,-2]

array([[13, 18, 23],
       [28, 33, 38],
       [43, 48, 53]])

In [43]:
x[1,1:,-1]

array([34, 39])

In [45]:
x[:,:,2:]

array([[[12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]],

       [[27, 28, 29],
        [32, 33, 34],
        [37, 38, 39]],

       [[42, 43, 44],
        [47, 48, 49],
        [52, 53, 54]]])