In [35]:
import numpy as np

In [38]:
x = np.array([10,20,30,40,50])
x+100


array([110, 120, 130, 140, 150])

In [5]:
x = np.array([[1,2],[3,4],[5,6]])

In [6]:
np.transpose(x)

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
y=np.array(([2,4,7,8],
            [1,2,3,1]))

In [8]:
np.dot(x,y)

array([[ 4,  8, 13, 10],
       [10, 20, 33, 28],
       [16, 32, 53, 46]])

In [9]:
from numpy.linalg import inv  #import linear algebra module from numpy

In [10]:
a=np.array(([1,2],[3,4]))

In [11]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
type(a)

numpy.ndarray

In [13]:
import numpy as np
a = np.array([10,20,30,40,50])
type(a)
b = [10,50,60]
type(a)

numpy.ndarray

In [14]:
c = np.array(b)
type(c)
print(c)

[10 50 60]


In [15]:
[ v + 100 for v in b ] #adding elements for b which is a list and not a array 

[110, 150, 160]

In [16]:
c+100 # direct addition for array


array([110, 150, 160])

In [17]:
d = np.arange(5)
print(d)

[0 1 2 3 4]


In [18]:
e = np.arange(10)+1
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
np.random.random(5) #Take any random numbers

array([0.49561706, 0.74845215, 0.76779635, 0.48123198, 0.81427186])

In [20]:
np.random.random(5)*100 # for two digit

array([55.28231078, 99.39273411, 52.76105291,  6.50517628, 96.08450827])

In [21]:
np.random.random(5)*1000 # for three digit

array([813.18692941, 785.76560701, 639.12462667, 233.5742286 ,
       150.64519193])

In [22]:
np.random.seed(10) #new values in elements are not taken if the seed command is used before the random 
np.random.random(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [23]:
x=np.arange(10)+100
print(x)

[100 101 102 103 104 105 106 107 108 109]


In [24]:
x[2]

102

In [25]:
x[-1]  #from back

109

In [26]:
x[3:7]

array([103, 104, 105, 106])

In [27]:
print(x)

[100 101 102 103 104 105 106 107 108 109]


In [28]:
x[-4:]

array([106, 107, 108, 109])

In [29]:
x[:5]

array([100, 101, 102, 103, 104])

In [30]:
np.shape(x)

(10,)

In [40]:
np.ndim(x)

1

In [41]:
y = x.reshape((5,2))

In [32]:
print(y)

[[2 4 7 8]
 [1 2 3 1]]


In [34]:
y.shape

(2, 4)

In [44]:
y.ndim

2

In [45]:
p=np.arange(90)+5

In [46]:
print(p)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [48]:
import numpy as np

In [50]:
print(np.version)

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [51]:
import numpy as np
a = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [52]:
b=np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [54]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [56]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [57]:
e.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
import numpy as np

In [59]:
f = np.array([1,2,3])

In [60]:
g = np.array([4,5,6])

In [63]:
print('Horizontal Append:',np.hstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]


In [64]:
print('Vertical Append:', np.vstack((f,g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [65]:
A = np.matrix(np.ones((4,4)))

In [66]:
np.array(A)[2] = 2
print(A)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.asarray(A)[2] = 2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]
